### ISSUE TITLE
Travis CI support?

### ISSUE THREAD

**Issue by richelbilderbeek** [franciscorichter/dmea#1]
If you'd like to have these buttons...

![buildbadges](https://cloud.githubusercontent.com/assets/2098230/20529284/f45cbb8a-b0cf-11e6-8574-c62ab2990aa8.png)

... that will show you if your package builds, has correct style, etc (like [in this video by me](http://streaming3.service.rug.nl/p2gplayer/Player.aspx?id=c9GNy2)), I volunteer to add it.

You will need to use your GitHub login to activate Travis CI and Codecov, which will be easy.

**Comment by franciscorichter** [comment]
I think that is a great idea. Thanks Richel!, let's do it :muscle:

**Comment by richelbilderbeek** [comment]
Pull Request is sent :-)
